version: "3"
networks:
  expense:
volumes:
  mysql:  # docker volume create mysql
services:
  mysql:
    image: pavankalyan111/mysql
    container_name: mysql # --name mysql
    volumes:
    - mysql:/var/lib/mysql # -v mysql:/var/lib/mysql
    network:
     - expense
  backend:
    image: pavankalyan111/backend
    container_name: backend
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on:
    - mysql
    network:
     - expense
  frontend:
    image: pavankalyan111/frontend
    container_name: frontend
    ports:
    - 8080:80
    depends_on:
    - backend
    network:
     - expense